# mybatis
mybatis:
  mapper-locations: classpath*:mappings/**/*.xml
spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/admin-beacon?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=60000&rewriteBatchedStatements=true
    username: ${db.user}
    password: ${db.password}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 5000
      validation-timeout: 3000
